version: '3.8'
services:
  frontend:
    build: ./frontend
    volumes: 
      - app-frontend:/app

      
  backend:
    build: .
    privileged: true
    ports:
      - 8080:8080
    command: bash -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn --bind 0.0.0.0:8080 videostorage.wsgi"
    volumes:
      - app-frontend:/frontend
    depends_on:
      - frontend
    restart:
      always
      
  nginx:
    build: ./nginx
    ports: 
      - 8000:80
    depends_on:
      - backend
    volumes:
      - app-frontend:/frontend
      
volumes:
  app-frontend:
