# Generated by Django 3.2.8 on 2021-10-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='end_time',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
