# Generated by Django 3.2.8 on 2021-10-22 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_item_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='is_deleted',
        ),
    ]
