# Generated by Django 3.2.9 on 2021-11-24 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_record_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=128)),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'action',
            },
        ),
        migrations.AlterField(
            model_name='record',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.action'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
