# Generated by Django 3.2.9 on 2021-11-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_record_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='license_table',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
