# Generated by Django 3.2.9 on 2021-11-26 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_car_license_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField()),
                ('delivered', models.BooleanField(default=False)),
                ('record_status', models.BooleanField(null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.car')),
            ],
            options={
                'db_table': 'request',
            },
        ),
    ]
