# Generated by Django 3.2.9 on 2021-11-29 07:06

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_record_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='filenames',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), null=True, size=3),
        ),
        migrations.AlterField(
            model_name='request',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.car'),
        ),
    ]
