# Generated by Django 3.2.9 on 2021-11-29 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_remove_request_filenames'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='item',
            new_name='action',
        ),
        migrations.AlterField(
            model_name='record',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='records', to='mainapp.request'),
        ),
    ]
