# Generated by Django 3.2.9 on 2021-11-29 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20211129_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='mainapp.request'),
        ),
    ]
