# Generated by Django 3.2.9 on 2021-11-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_alter_record_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
