# Generated by Django 3.2.9 on 2021-12-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_alter_record_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='ip_address',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='last_seen',
            field=models.DateTimeField(null=True),
        ),
    ]
